version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
clone_depth: 1

branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

configuration: Release

install:
  - git submodule update --init --recursive

build_script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
  - bash coverage.sh
  - bash coveralls.sh

deploy: off